config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users' => 'users#index'
  get '/users/end_session'

  post '/users' => 'users#create'

  get 'messages' => 'messages#index'
  post '/messages' => 'messages#create'

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	require 'translator_api'

  belongs_to :user

  before_save :translate_content

  def icon
  	case self.user.dialect
  		when User::YODA
  			return 'fighter-jet'
  		when User::VALLEY
  			return 'shopping-bag'
  		when User::PIRATE
  			return 'flag'
		end		
  end

  def translate_content
  	if self.user.dialect == User::PIRATE
  		self.content = TranslatorApi.translate_pirate content
  	else
  		self.content = TranslatorApi.translate_other self.user.dialect, self.content
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
	after_create :set_active

	validates :name, presence: true

	has_many :messages

	PIRATE = 'pirate'
	YODA = 'yoda'
	VALLEY = 'valley'

	def set_active
		update active: true
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	
	def index
		@messages = Message.all
		@new_message = User.find(session[:user_id]).messages.build
	end

	def create
    @message = User.find(session[:user_id]).messages.build(message_params)

    if @message.save
      sync_new @message
    end

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

	private
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = User.new
	end

	def create
		@user = User.new user_params
		if @user.save
			session[:user_id] = @user.id
			redirect_to messages_url
		else 
			render :index
		end
	end

	def end_session
		User.find(session[:user_id]).update active: false
		session.delete :user_id
		redirect_to index
	end

	def user_params
    params.require(:user).permit(:name, :dialect)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatRoom</title>
    <%= csrf_meta_tags %>
    <%= include_sync_config %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<div class="container wrapper">
	<div class='pull-left messages-container'>
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Messages</h3>
		  </div>
		  <div class="panel-body messages">
		    <%= sync partial: 'message_row', collection: @messages %>
				<%= sync_new partial: 'message_row', resource: Message.new, direction: :append %>
		  </div>
		  	
		</div>
	</div>		

	<div class='pull-right'>
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Users</h3>
		  </div>
		  <div class="panel-body users">
				<ul class='list-group'>
				<% User.all.each do |user| %>
					<%= content_tag :li, user.name, class: 'list-group-item' if user.active? %>
				<% end %>
				</ul>
			</div>
		</div>
	</div>

	<div class='clearfix'></div>
	<div class="panel panel-default">
		<div class="panel-footer">
			<%= form_for @new_message, remote: true do |f| %>
				<div class="form-group">
			 		<%= f.text_field :content, class: 'form-control' %>
			 		<br>
		 			<div class= 'text-center'>
		  			<%= link_to 'Log out', users_end_session_path, class: 'btn btn-danger' %>
		  		</div>
		  	</div>
			<% end %>
		</div>
	</div>
</div>

app/views/sync/messages/_message_row.html.erb
<%= "[#{message.created_at}]" + ' ' + message.user.name +  ': ' + message.content %>
<%= fa_icon message.icon %>
<br>

app/views/users/index.html.erb
<div class="container">
	<%= form_for @user, html: { class: 'form-horizontal' } do |f| %>
		<% if @user.errors.any? %>
	    <div id="error_explanation">
	     <ul>
	      <% @user.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="form-group">
			<%= f.label :name, class: 'label-light' %>
			<%= f.text_field :name, class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.label :dialect, class: 'label-light' %>
			<%= f.select(:dialect) do %>
		  	<% [User::PIRATE, User::YODA, User::VALLEY].each do |c| -%>
		    <%= content_tag(:option, c, value: c) %>
		  <% end %>
	  </div>
	<% end %>	

		<%= f.submit 'Go!', class: 'btn btn-default' %>
	<% end %>
</div>